services:

    App\Service\Mail\Mailer\MailerInterface:
        class: App\Service\Mail\Mailer\SendmailMailer

    App\Service\Newsletter\NewsletterService:
        autowire: true
        public: true

    App\Service\Newsletter\MonitoringNewsletterService:
        decorates: App\Service\Newsletter\NewsletterService
        arguments: [ '@.inner' ]
