mailer:
    smtp:
        enabled: true
        username: '%env(MAILER_USERNAME)%'
        password: '%env(MAILER_PASSWORD)%'
        host: '%env(MAILER_HOST)%'
        port: '%env(int:MAILER_PORT)%'
