services:

    App\Service\Mail\Mailer\MailerInterface:
        # the first argument is the class and the second argument is the static method
        factory: [ 'App\Service\Mail\Mailer\MailerFactory', 'createDefaultMailer' ]
        public: true
