services:

    logger:
        class: 'App\Service\Logger\EchoLogger'

    App\Service\Mail\Mailer\SendmailMailer: ~

    App\Service\Mail\Mailer\MailerInterface: '@App\Service\Mail\Mailer\SendmailMailer'

    App\Service\Newsletter\NewsletterService:
        autowire: true
        public: true
        calls:
            - [ 'setLogger', [ '@logger' ] ]
