parameters:
    smtp_transport_username: 'user'
    smtp_transport_password: 'password'
    smtp_transport_host: 'example.com'
    smtp_transport_port: 25

services:

    App\Service\Mail\Transport\SendmailTransport:
        tags:
            - { name: 'mail.transport', priority: 20 }

    App\Service\Mail\Transport\SmtpTransport:
        arguments:
            $username: '%smtp_transport_username%'
            $password: '%smtp_transport_password%'
            $host: '%smtp_transport_host%'
            $port: '%smtp_transport_port%'
        tags:
            - { name: 'mail.transport', priority: 50 }

    App\Service\Mail\Mailer\ChainMailer:
        public: true
        arguments:
            - !tagged_iterator mail.transport
